name: Deploy NestJS to Linode

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/paygen-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Linode
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Pulling latest Docker image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/paygen-api:latest

            echo "Stopping existing container (if any)..."
            docker stop paygen-api-container || true

            echo "Removing existing container (if any)..."
            docker rm paygen-api-container || true

            echo "Running new container..."
            docker run -d \
              --name paygen-api-container \
              -p 80:${{ vars.PORT }} \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e NODE_ENV="${{ vars.NODE_ENV }}" \
              -e PORT="${{ vars.PORT }}" \
              -e API_PREFIX="${{ vars.API_PREFIX }}" \
              --restart always \
              ${{ secrets.DOCKERHUB_USERNAME }}/paygen-api:latest

            echo "Deployment complete!"
